const main = document.querySelector('#main');
const menu = document.querySelector('.menu-button');
const nav = document.querySelector('.topnav');
menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open)});
nav.addEventListener('click',()=>nav.classList.remove('open'));

const palette = ['linear-gradient(135deg,#071c32,#2d75bc)','linear-gradient(135deg,#222851,#785f9f)','linear-gradient(135deg,#163c42,#6fa28f)','linear-gradient(135deg,#402a58,#b483d0)','linear-gradient(135deg,#2e4057,#d0815b)','linear-gradient(135deg,#113c72,#77acd8)'];
const slugify=s=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[“”‘’?'’:—–]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,90);
debates.forEach(d=>d.slug=slugify(d.title));
const detailHref=d=>`#/debate/${d.slug}`;
const excerpt=d=>{
 const t=d.title.toLowerCase();
 if(t.includes('v1')) return 'Does primary visual cortex build a map of the external world, or something else?';
 if(t.includes('probabilistic')) return 'How should uncertainty and probability figure in accounts of neural computation and perception?';
 if(t.includes('representations')) return 'What makes a representation explanatorily useful, and what should it enable?';
 if(t.includes('world')) return 'Does the brain build an internal model of the world, and what would count as evidence?';
 if(t.includes('ventral')) return 'What shapes visual representations, and how should models explain ventral-stream function?';
 return `A CCN Generative Adversarial Collaboration on ${d.topic.toLowerCase()}.`;
}
function card(d,i=0){return `<article class="debate-card"><div class="thumb" style="--thumb:${palette[(d.year+i)%palette.length]}">${d.recording?'<span class="watch-badge">▶ Recording</span>':'<span class="watch-badge">CCN 2026</span>'}</div><div class="card-body"><div class="eyebrow">${d.year} · ${d.topic}</div><h3>${d.title}</h3><p>${excerpt(d)}</p><div class="card-bottom"><span class="pill">${d.year}</span><a href="${detailHref(d)}">Explore →</a></div></div></article>`}
function home(){const featured=debates.find(d=>d.title==='Is V1 a cognitive map?'); const orderedDebates=[...debates].sort((a,b)=>b.year-a.year);return `
<section class="hero"><div class="shell hero-grid"><div><div class="kicker">Generative Adversarial Collaborations</div><h1 class="display">Where the field’s biggest questions are argued out.</h1><p class="lead">Leading researchers with competing theories work together to identify experiments, analyses, or theoretical advances that could resolve major debates in cognitive computational neuroscience.</p><div class="actions"><a class="btn primary" href="#/debates">▶ Watch the debates</a><a class="btn secondary" href="#/about">What is a GAC?</a></div></div><div class="brain-art hero-photo-wrap" aria-hidden="true"><div class="hero-photo"></div></div></div></section>
<section class="section"><div class="shell"><div class="feature-card"><div class="visual"><div class="stage"><span class="person"></span><span class="person"></span><span class="person"></span><span class="person"></span><span class="person"></span></div><div class="play">▶</div></div><div class="feature-copy"><div class="eyebrow">Featured debate</div><h3>${featured.title}</h3><p class="names">${featured.people}</p><div class="meta-row"><span class="pill">CCN ${featured.year}</span>${featured.recording?`<a class="resource" href="${featured.recording}" target="_blank">Workshop recording ↗</a>`:''}<a class="resource" href="${detailHref(featured)}">Debate page →</a></div><p>${excerpt(featured)}</p></div></div><div class="stats"><div class="stat"><strong>${debates.length}</strong><span>GACs, 2020–2026</span></div><div class="stat"><strong>100+</strong><span>Researchers</span></div><div class="stat"><strong>${new Set(debates.map(d=>d.year)).size}</strong><span>Years</span></div></div></div></section>
<section class="section tight"><div class="shell"><div class="section-head"><div><div class="eyebrow">Watch · read · explore</div><h2>All debates</h2></div></div><div class="cards">${orderedDebates.map(card).join('')}</div></div></section>
<section class="section pale"><div class="shell"><div class="section-head"><div><div class="eyebrow">Browse differently</div><h2>Explore by topic</h2></div></div><div class="topic-chips">${['Vision','Representation','NeuroAI','World models','Memory','Learning','Decision-making','Methods'].map(t=>`<a class="topic-chip" href="#/topics/${encodeURIComponent(t)}">${t}</a>`).join('')}</div></div></section>
<section class="section"><div class="shell"><div class="section-head"><div><div class="eyebrow">From disagreement to research</div><h2>How GACs work</h2></div><a class="link-arrow" href="#/about">Learn more →</a></div><div class="how-grid"><div class="step"><div class="step-num">1</div><h3>Debate</h3><p>Researchers articulate competing perspectives and identify the points of genuine disagreement.</p></div><div class="step"><div class="step-num">2</div><h3>Collaborate</h3><p>The team develops concrete experiments, analyses, simulations, or theoretical steps that could move the debate forward.</p></div><div class="step"><div class="step-num">3</div><h3>Publish</h3><p>The workshop feeds into a collaborative position paper and continued work, with progress presented back to CCN.</p></div></div></div></section>`}
function debatesPage(initialTopic=''){return `<section class="page-hero"><div class="shell"><div class="eyebrow">The archive, re-organized around questions</div><h1 class="page-title">The debates</h1><p class="page-intro">Every CCN Generative Adversarial Collaboration from 2020 through the three accepted 2026 GACs. Search by scientific question, researcher, year, or topic.</p></div></section><section class="section tight"><div class="shell"><input id="search" class="searchbox" type="search" placeholder="Search debates or researchers…" aria-label="Search debates"><div class="filterbar" id="yearFilters">${['All',2026,2025,2024,2023,2022,2021,2020].map((y,i)=>`<button class="filter-btn ${i===0?'active':''}" data-year="${y}">${y}</button>`).join('')}</div><div id="debateResults" class="cards"></div></div></section>`}
function wireDebateFilters(){const search=document.querySelector('#search'),results=document.querySelector('#debateResults');let year='All';let preset=decodeURIComponent(location.hash.split('/topics/')[1]||'');function render(){const q=(search.value||preset).toLowerCase();const list=debates.filter(d=>(year==='All'||String(d.year)===String(year))&&(!q||`${d.title} ${d.people} ${d.topic}`.toLowerCase().includes(q)));results.innerHTML=list.length?list.map(card).join(''):'<div class="empty">No debates match this filter.</div>'}search.addEventListener('input',()=>{preset='';render()});document.querySelectorAll('[data-year]').forEach(b=>b.onclick=()=>{year=b.dataset.year;document.querySelectorAll('[data-year]').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()});if(preset)search.value=preset;render()}
function archivePage(){const years=[2026,2025,2024,2023,2022,2021,2020];return `<section class="page-hero"><div class="shell"><div class="eyebrow">Chronological index</div><h1 class="page-title">Archive</h1><p class="page-intro">The complete GAC programme by year, preserving the historical structure while making every debate directly discoverable.</p></div></section><section class="section tight"><div class="shell">${years.map(y=>`<div class="year-block"><h2 class="year-title">${y}</h2><div class="cards">${debates.filter(d=>d.year===y).map(card).join('')}</div></div>`).join('')}</div></section>`}
function aboutPage(){return `<section class="page-hero"><div class="shell"><div class="eyebrow">What is a GAC?</div><h1 class="page-title">Disagreement, made generative.</h1><p class="page-intro">A Generative Adversarial Collaboration brings scientists with competing perspectives together to formulate a shared research agenda for resolving an important debate.</p></div></section><section class="section"><div class="shell detail-grid"><div class="detail-main"><div class="detail-section"><h2>Why GACs exist</h2><p>Scientific debates can persist when groups develop evidence in parallel without directly agreeing on what observations would discriminate between their views. The CCN GAC programme is designed to create direct dialogue, sharpen disagreements, and turn them into concrete research plans.</p></div><div class="detail-section"><h2>Three ingredients</h2><div class="process-list"><div class="process-item"><h3>Collaboration</h3><p>Scientists from different communities develop shared language and work toward progress as a field.</p></div><div class="process-item"><h3>Adversarial discourse</h3><p>The competition is between theories, not people. Competing views are made explicit so they can be tested.</p></div><div class="process-item"><h3>Generativity</h3><p>The interaction should produce new questions, experiments, hypotheses, theoretical positions, and ultimately a collaborative paper.</p></div></div></div><div class="detail-section"><h2>The cycle</h2><div class="timeline"><div><strong>1. Form a core team</strong>Include at least two members willing to articulate competing viewpoints.</div><div><strong>2. Proposal + community feedback</strong>Selected proposals are shared and strengthened through feedback from the CCN community.</div><div><strong>3. Kickoff workshop at CCN</strong>An interactive debate focuses on points of contention and possible ways to arbitrate them.</div><div><strong>4. Position paper</strong>The team documents the debate and lays out a concrete experimental or theoretical path forward.</div><div><strong>5. Return to CCN</strong>GACs are invited to report progress at the following annual meeting.</div></div></div></div><aside class="detail-side"><div class="callout"><strong>In the original programme</strong><p>CCN describes the goal as making concrete plans to address important debates — and beginning to implement those plans.</p><a class="link-arrow" href="${ORIGINAL_HOME}" target="_blank">Original GAC website ↗</a></div><h3>Further reading</h3><p><a class="link-arrow" href="https://doi.org/10.1016/j.tics.2025.02.005" target="_blank">TICS paper on GACs ↗</a></p><p><a class="link-arrow" href="${ORIGINAL_SUBMIT}" target="_blank">Detailed practical guide / call ↗</a></p></aside></div></section>`}
function submitPage(){return `<section class="page-hero"><div class="shell"><div class="eyebrow">Propose a future GAC</div><h1 class="page-title">Turn a live controversy into a research programme.</h1><p class="page-intro">The current CCN process asks teams to define a genuine scientific disagreement, assemble a core team, and propose an engaging workshop plus a route toward a collaborative position paper.</p></div></section><section class="section"><div class="shell detail-grid"><div><div class="callout"><strong>2026 cycle</strong><p>The 2026 call is now represented here for reference. For live deadlines and future calls, use the official CCN website.</p><a class="btn primary" href="https://ccneuro.org" target="_blank">Check current CCN calls ↗</a></div><div class="detail-section"><h2>What a strong GAC proposal needs</h2><div class="process-list"><div class="process-item"><h3>A real disagreement</h3><p>Competing hypotheses, theoretical frameworks, or interpretations that matter to cognitive computational neuroscience.</p></div><div class="process-item"><h3>A team able to disagree productively</h3><p>A core group including at least two people willing to defend or articulate competing views while collaborating in good faith.</p></div><div class="process-item"><h3>A route to arbitration</h3><p>Concrete ideas for experiments, simulations, analyses, or theory that could distinguish the competing perspectives.</p></div><div class="process-item"><h3>An interactive workshop</h3><p>The format should be a debate and community interaction, not a sequence of independent symposium talks.</p></div></div></div><div class="detail-section"><h2>Typical annual rhythm</h2><div class="timeline"><div><strong>January</strong>Call for proposals</div><div><strong>March</strong>Proposal deadline</div><div><strong>Mid-April</strong>Selection decisions and community feedback</div><div><strong>May–July</strong>Workshop preparation with the Program Committee</div><div><strong>August</strong>Kickoff workshops at CCN</div><div><strong>Following year</strong>Position paper work and progress presentation</div></div></div></div><aside class="detail-side"><h3>Official source</h3><p>The formal requirements can change from year to year.</p><a class="btn secondary" href="${ORIGINAL_SUBMIT}" target="_blank">Read the original call ↗</a><h3 style="margin-top:30px">Contact</h3><p><a class="link-arrow" href="mailto:gac@ccneuro.org">gac@ccneuro.org</a></p></aside></div></section>`}
function detailPage(slug){const d=debates.find(x=>x.slug===slug);if(!d)return `<section class="section"><div class="shell empty">Debate not found. <a href="#/debates">Return to all debates</a>.</div></section>`;return `<section class="page-hero"><div class="shell detail-grid"><div class="detail-main"><div class="eyebrow">CCN ${d.year} · ${d.topic}</div><h1>${d.title}</h1><p class="page-intro">${excerpt(d)}</p><div class="actions">${d.recording?`<a class="btn primary" href="${d.recording}" target="_blank">▶ Watch workshop ↗</a>`:''}<a class="btn secondary" href="${d.paper||d.archive}" target="_blank">${d.paper?'Read position paper':'Original archive'} ↗</a></div></div><aside class="detail-side"><h3>Participants</h3><p class="people">${d.people}</p></aside></div></section><section class="section"><div class="shell detail-grid"><div>${d.recording?`<div class="detail-section"><h2>Workshop recording</h2><a class="video-link" href="${d.recording}" target="_blank"><span class="icon">▶</span><span><strong>Watch the CCN ${d.year} workshop</strong><br><small>Opens the original recording in a new tab</small></span></a></div>`:''}<div class="detail-section"><h2>The collaboration</h2><p>This page foregrounds the scientific question and the people involved. Proposal and publication status remain linked back to the official GAC archive so the redesign does not silently invent or overwrite the programme record.</p></div><div class="detail-section"><h2>Why this belongs in Great Debates</h2><p>The GAC format is built around making competing perspectives explicit and asking what evidence, analyses, or theoretical progress could genuinely move the disagreement forward.</p></div></div><aside class="detail-side"><h3>Source record</h3><p><a class="link-arrow" href="${d.archive}" target="_blank">View in original GAC archive ↗</a></p>${d.paper?`<p><a class="link-arrow" href="${d.paper}" target="_blank">Position paper ↗</a></p>`:''}<h3 style="margin-top:30px">Browse</h3><p><a class="link-arrow" href="#/topics/${encodeURIComponent(d.topic)}">More on ${d.topic} →</a></p><p><a class="link-arrow" href="#/archive">Archive by year →</a></p></aside></div></section>`}
function route(){const hash=location.hash||'#/';const parts=hash.slice(2).split('/');const root=parts[0]||'';if(root==='')main.innerHTML=home();else if(root==='debates'){main.innerHTML=debatesPage();wireDebateFilters()}else if(root==='topics'){main.innerHTML=debatesPage(parts[1]||'');wireDebateFilters()}else if(root==='archive')main.innerHTML=archivePage();else if(root==='about')main.innerHTML=aboutPage();else if(root==='submit')main.innerHTML=submitPage();else if(root==='debate')main.innerHTML=detailPage(parts.slice(1).join('/'));else main.innerHTML=home();window.scrollTo(0,0)}
window.addEventListener('hashchange',route);route();
