const ORIGINAL_ARCHIVE = 'https://gac.ccneuro.org/gacs-by-year';
const ORIGINAL_HOME = 'https://gac.ccneuro.org';
const ORIGINAL_SUBMIT = 'https://gac.ccneuro.org/call-for-proposals';

const debates = [
{year:2026,title:'Is NeuroAI adopting the right methods and theoretical frameworks to advance our understanding of mind and brain?',people:'Jeffrey Bowers, Nicholas Baker, Jenelle Feather, Anya Ivanova, Grace Lindsay, Aran Nayebi, Milton Montero, Martin Schrimpf',topic:'NeuroAI',recording:null,status:'CCN 2026 kickoff workshop'},
{year:2026,title:'Do World Models Emerge in Neural Networks Trained for Prediction?',people:'Eivinas Butkus, Alexa Tartaglini, Josh Ying, Sonia Joseph, Brian Cheung, Jennifer Hu, Niko Kriegeskorte, Ellen Su, Solim LeGris, John Morrison, Ilker Yildirim, Patrick Butlin, Brenden Lake',topic:'World models',recording:null,status:'CCN 2026 kickoff workshop'},
{year:2026,title:'Representations or Transformations: What Should Models of Neural Population Activity Explain?',people:'Julian Kędys, Cezary Mazurek, SueYeon Chung, Sarah Harvey, Sophia Sanborn, Il Memming Park, Maneesh Sahani, Thomas Anderson Keller',topic:'Representation',recording:null,status:'CCN 2026 kickoff workshop'},
{year:2025,title:'Clarifying and reconciling different perspectives on the structure of the neural code',people:'Meenakshi Khosla, Nancy Kanwisher, Stefano Fusi, Niko Kriegeskorte, Tatiana Engel, Marcus Benna, David Klindt, Carsen Stringer',topic:'Neural coding',recording:'https://hva-uva.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=e9a2925e-d68c-4740-a267-b32100834d27'},
{year:2025,title:'What shapes the ventral visual system in infancy — innate biases or experience?',people:'Marieke Mur, Talia Konkle, Dan Yamins, Moritz Köster, Michael Arcaro, Nick Turk-Browne, Rebecca Saxe, Rhodri Cusack',topic:'Vision',recording:'https://hva-uva.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=89c5533b-9615-45d2-a050-b3210088af1d'},
{year:2025,title:'What Benchmarks are Useful for Cognitive Science?',people:'Susanne Haridi, Marcel Binz, Rodrigo Carrasco-Davis, Clementine Domine, Erin Grant, Alireza Modirshanechi',topic:'Benchmarks',recording:'https://hva-uva.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=60c9e905-40ce-4f1d-a49e-b32100898568'},
{year:2024,title:'Is V1 a cognitive map?',people:'Paul Linton, David Heeger, Tony Movshon, Lars Muckli, Hendrikje Nienborg, Paolo Papale, Andrew Parker, Lucy Petro, Pieter Roelfsema, Petra Vetter, Li Zhaoping, Cheng Xue, Nikolaus Kriegeskorte',topic:'Vision',recording:'https://www.youtube.com/live/mJOuWKTixX0'},
{year:2024,title:'Attending to errors in predictive coding: a collaborative community experiment through the OpenScope program',people:'Jerome Lecoq, Michael Berry, Colleen Gillon, Konrad Kording',topic:'Predictive coding',recording:'https://www.youtube.com/watch?v=C6jB3BoD_iE'},
{year:2023,title:'Reconciling the dichotomy between Sherringtonian and Hopfieldian views on neural computations',people:'Dongyan Lin, Arna Ghosh, Jonathan Cornford, James Whittington, Tatiana Engel, David Barack, John Krakauer, Daniel Levenstein',topic:'Neural computation',recording:'https://www.youtube.com/watch?v=cl_Wa7CGm7A'},
{year:2023,title:'Comparing artificial and biological networks: are we limited by tools, hypotheses or data?',people:'Meenakshi Khosla, N. Apurva Ratan Murty, Tal Golan, Jenelle Feather, Katherine Hermann, Aran Nayebi, Jessica Thompson, SueYeon Chung, Alex Williams, Rosa Cao, Radoslaw Martin Cichy, Bradley Love, Kalanit Grill-Spector, James DiCarlo',topic:'NeuroAI',recording:'https://www.youtube.com/watch?v=LSczBZBHVkM'},
{year:2022,title:'How can we optimally use neuroscience data to guide the next generation of brain models of primate visual and linguistic cognition?',people:'Greta Tuckute, Dawn Finzi, Eshed Margalit, Joel Zylberberg, SueYeon Chung, Alona Fyshe, Evelina Fedorenko, Nikolaus Kriegeskorte, Jacob Yates, Kalanit Grill-Spector, Kohitij Kar',topic:'Brain models',recording:'https://www.youtube.com/watch?v=Qbzi3gVbxYM'},
{year:2022,title:'To what extent does the brain simulate the external world?',people:'Kevin Smith, Todd Gureckis, Marcelo Mattar, Kelsey Allen, Fred Callaway, Ernest Davis, Judith Fan, Tom Griffiths, Jessica Hamrick, Wei Ji Ma, Kimberly Stachenfeld, Joshua Tenenbaum, Tomer Ullman',topic:'World models',recording:'https://www.youtube.com/watch?v=CtZyMraHjSA'},
{year:2022,title:'What is the place of planning?',people:'Malcolm A. MacIver, Nathaniel D. Daw, German Espinosa, Jessica B. Hamrick, Mark K. Ho, A. David Redish, Bradly C. Stadie, Jane X. Wang',topic:'Planning',recording:'https://www.youtube.com/watch?v=l1A1fouQg7E'},
{year:2021,title:'How does the brain combine generative models and direct discriminative computations in high-level vision?',people:'Benjamin Peters, James J. DiCarlo, Todd Gureckis, Ralf Haefner, Leyla Isik, Joshua Tenenbaum, Talia Konkle, Thomas Naselaris, Kimberly Stachenfeld, Zenna Tavares, Doris Tsao, Ilker Yildirim, Nikolaus Kriegeskorte',topic:'Vision',recording:'https://www.youtube.com/watch?v=bEG4T18le5g'},
{year:2021,title:'What makes representations “useful”?',people:'Ben Baker, Richard Lange, Alessandro Achille, Rosa Cao, Nikolaus Kriegeskorte, Odelia Schwartz, Xaq Pitkow',topic:'Representation',recording:'https://www.youtube.com/watch?v=PRWvL6p8lM8',paper:'https://nbdt.scholasticahq.com/article/129909-use-and-usability-concepts-of-representation-in-philosophy-neuroscience-cognitive-science-and-computer-science'},
{year:2021,title:'How does visual experience shape representations and transformations along the ventral stream?',people:'Marina Bedny, Nancy Kanwisher, Olivier Collignon, Ilker Yildirim, Elizabeth Saccone, Apurva Ratan Murty, Stefania Mattioni',topic:'Vision',recording:'https://www.youtube.com/watch?v=bccDdOKjiPg'},
{year:2021,title:'What constitutes understanding of ventral pathway function?',people:'Charles Connor, Gabriel Kreiman, Carlos R Ponce, Carl Craver, Margaret Livingstone, Martin Schrimpf, Binxu Wang',topic:'Vision',recording:'https://www.youtube.com/watch?v=v8dyIk0pEaY'},
{year:2020,title:'Competing theories of probabilistic computations in the brain',people:'Ralf Haefner, Jeff Beck, Cristina Savin, Mehrdad Salmasi, Eszter Vertes, Xaq Pitkow',topic:'Probabilistic inference',recording:'https://www.youtube.com/watch?v=kn9f1fxxits'},
{year:2020,title:'Is it that simple? The use of linear models in cognitive neuroscience',people:'Anna A. Ivanova, Martin Schrimpf, Stefano Anzellotti, Noga Zaslavsky, Evelina Fedorenko, Leyla Isik',topic:'Methods',recording:'https://www.youtube.com/watch?v=UI5KclR71IE'},
{year:2020,title:'Is perception probabilistic?',people:'Dobromir Rahnev, Ned Block, Rachel N. Denison, Janneke Jehee',topic:'Perception',recording:'https://www.youtube.com/watch?v=iE8-Lpm89zA'},
{year:2020,title:'Generalization of information — integrative encoding or category-based inference?',people:'Jessica E. Taylor, Aurelio Cortese, Helen C. Barron, Xiaochuan Pan, Masamichi Sakagami, Dagmar Zeithamova',topic:'Memory',recording:'https://www.youtube.com/watch?v=146N204Ju0c',paper:'https://nbdt.scholasticahq.com/article/27687-how-do-we-generalize'},
{year:2020,title:'Dimensionality and flexibility of learning in biological recurrent neural networks',people:'Roy H. Eyono, Ellen Boven, Arna Ghosh, Joseph Pemberton, Franz Scherr, Claudia Clopath, Rui Ponte Costa, Wolfgang Maass, Blake A. Richards, Cristina Savin, Katharina Wilmes, Luke Y. Prince',topic:'Learning',recording:'https://www.youtube.com/watch?v=SErwiM693AI'},
{year:2020,title:'Do grid codes afford generalization and flexible decision-making?',people:'Linda Q. Yu, Seongmin A. Park, Sarah C. Sweigart, Erie D. Boorman, Matthew R. Nassar',topic:'Decision-making',recording:'https://www.youtube.com/watch?v=aDBjuFHucts'}
];

debates.forEach((d,i)=>{d.id = `${d.year}-${String(i+1).padStart(2,'0')}`; d.archive=ORIGINAL_ARCHIVE;});
